# Generated by Django 2.2 on 2020-04-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created',), 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='articlecolumn',
            options={'verbose_name_plural': '栏目'},
        ),
    ]
